//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareOnlineStore.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class HardwareOnlineStoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HardwareOnlineStoreSettings defaultInstance = ((HardwareOnlineStoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HardwareOnlineStoreSettings())));
        
        public static HardwareOnlineStoreSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
